version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - POSTGRES_PASSWORD=$YU_POSTGRESQL_PASSWORD
      - YU_SPOTIFY_CLIENT_ID=$YU_SPOTIFY_CLIENT_ID
      - YU_SPOTIFY_CLIENT_SECRET=$YU_SPOTIFY_CLIENT_SECRET
    image: yliang/spotify-experiment-framework:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - spotify-experiment-framework-net
      - nginx-net
  postgresql:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=$YU_POSTGRESQL_PASSWORD
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - spotify-experiment-framework-net
networks:
  spotify-experiment-framework-net:
    driver: overlay
    attachable: true
  nginx-net:
    external: true
